name: CI


on: 
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    working-directory: ./backend
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.18'

      - name: Test
        run: go test ./...
